# Generated by Django 2.2.18 on 2021-04-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210417_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
