# Generated by Django 2.2.18 on 2021-05-17 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('narration', models.CharField(max_length=255, null=True)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.Wallet')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
